# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main,master]
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown.yaml


permissions: write-all

jobs:
  pkgdown:
    runs-on: macos-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      # Optionally, set JULIA_DEPOT_PATH if find package installation issues
      # JULIA_DEPOT_PATH: /home/runner/.julia
    permissions:
      contents: write # This should be enough for pkgdown to deploy to gh-pages
    steps:
      - uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.11.5' # Ensure this version is stable and compatible with RCall
        env:
          # This helps ensure Julia installs packages into a predictable location
          JULIA_DEPOT_PATH: /home/runner/.julia

      # R-lib setup-r must happen BEFORE you try to get R_HOME
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true


      - name: Determine and set R_HOME for Julia
        shell: bash
        run: |
          # Get R_HOME after setup-r has configured R
          R_HOME_PATH=$(Rscript -e 'cat(R.home())')
          echo "Determined R_HOME_PATH: $R_HOME_PATH"
          # Export R_HOME for subsequent steps in the workflow
          echo "R_HOME=$R_HOME_PATH" >> $GITHUB_ENV
          echo "R_HOME environment variable set to $R_HOME_PATH for current and subsequent steps."
          # Also, set it for the current shell context (though GITHUB_ENV is primary for next steps)
          export R_HOME=$R_HOME_PATH
          echo "Verified R_HOME in current shell: $R_HOME"

      - name: Install and Configure Julia RCall
        shell: julia {0} # Run as a Julia script directly for better context
        run: |
          # Ensure R_HOME is explicitly set in Julia's ENV, drawing from the shell's environment
          ENV["R_HOME"] = get(ENV, "R_HOME", "") # Use get to avoid error if not set, though it should be now
          println("Julia's R_HOME environment variable: $(ENV["R_HOME"])")

          import Pkg
          println("Adding RCall.jl and Suppressor.jl...")
          Pkg.add("RCall")
          Pkg.add("Suppressor")
          Pkg.add("JuliaBUGS")

          println("Packages added. Testing RCall...")

          using RCall
          my_julia_range = 1:5; # Assign the range to a Julia variable
          @rput my_julia_range; # Now use @rput with the Julia variable name
          println("RCall test successful!")
          # Add any other Julia configurations or pre-compilations if necessary

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::., any::devtools
          needs: website

      - name: Install package
        run: Rscript -e 'devtools::install(build = TRUE, build_vignettes = TRUE, upgrade = "never")'

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = TRUE, install = TRUE)
        shell: Rscript {0}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
