name: pkgdown-macos

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch:

permissions: write-all

jobs:
  pkgdown:
    runs-on: macos-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      JULIA_DEPOT_PATH: /Users/runner/.julia
    permissions:
      contents: write

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Install JAGS (macOS-only)
      - name: Install JAGS
        run: |
          brew update
          brew install jags
          brew link --force jags

      # 3. Set up R
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'
          use-public-rspm: true

      # 4. Install rjags from source (requires JAGS)
      - name: Install rjags
        run: Rscript -e 'install.packages("rjags", type = "source")'

      # 5. Set R_HOME for Julia
      - name: Set R_HOME for Julia
        run: echo "R_HOME=$(Rscript -e 'cat(R.home())')" >> $GITHUB_ENV

      # 6. Set up Julia (macOS-only)
      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.11.5'
          arch: 'x64'

      # 7. Install Julia packages and test RCall
      - name: Install Julia packages
        shell: julia {0}
        run: |
          ENV["R_HOME"] = get(ENV, "R_HOME", "")
          import Pkg
          Pkg.add("RCall")
          Pkg.add("Suppressor")
          Pkg.add("JuliaBUGS")
          using RCall
          my_julia_range = 1:5
          @rput my_julia_range
          println("RCall test successful!")

      # 8. Setup Pandoc (macOS)
      - uses: r-lib/actions/setup-pandoc@v2

      # 9. Install R package dependencies
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::., any::devtools

      # 10. Install your R package with vignettes
      - name: Install package
        run: Rscript -e 'devtools::install(build = TRUE, build_vignettes = TRUE, upgrade = "never")'

      # 11. Build pkgdown site
      - name: Build site
        run: Rscript -e 'pkgdown::build_site_github_pages(new_process = TRUE, install = TRUE)'

      # 12. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
