name: pkgdown.yaml

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch:

permissions: write-all

jobs:
  pkgdown:
    runs-on: windows-latest

    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      JULIA_DEPOT_PATH: C:/julia

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      # 1. Set up R
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: '4.4.1'

      # 2. Install rjags (Windows binary)
      - name: Install rjags
        run: Rscript -e 'install.packages("rjags")'

      # 3. Set R_HOME for Julia
      - name: Set R_HOME for Julia
        run: echo "R_HOME=$(Rscript -e 'cat(R.home())')" >> $GITHUB_ENV

      # 4. Set up Julia (Windows installer)
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.11.5'
          architecture: 'x64'
          release: 'stable'

      # 5. Install Julia packages and test RCall
      - name: Install Julia packages
        shell: julia {0}
        run: |
          ENV["R_HOME"] = get(ENV, "R_HOME", "")
          import Pkg
          Pkg.add("RCall")
          Pkg.add("Suppressor")
          Pkg.add("JuliaBUGS")
          using RCall
          my_julia_range = 1:5
          @rput my_julia_range
          println("RCall test successful!")

      # 6. Setup Pandoc
      - uses: r-lib/actions/setup-pandoc@v2

      # 7. Install R package dependencies
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::., any::devtools
          needs: website

      # 8. Install your package with vignettes
      - name: Install package
        run: Rscript -e 'devtools::install(build = TRUE, build_vignettes = TRUE, upgrade = "never")'

      # 9. Build pkgdown site
      - name: Build site
        run: Rscript -e 'pkgdown::build_site_github_pages(new_process = TRUE, install = TRUE)'

      # 10. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
