name: pkgdown.yaml

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch:

permissions: write-all

jobs:
  pkgdown:
    runs-on: ubuntu-22.04   # Use Ubuntu 22.04 to get libjags-dev

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      # 1. Install system JAGS and headers
      - name: Install JAGS
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jags libjags-dev

      # 2. Ensure LD_LIBRARY_PATH includes JAGS library
      - name: Set library path for JAGS
        run: |
          export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
          echo "LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH" >> $GITHUB_ENV

      # 3. Set up R
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: '4.4.1'

      # 4. Install rjags from source
      - name: Install rjags from source
        run: Rscript -e 'install.packages("rjags", type = "source")'

      # 5. Set R_HOME for Julia
      - name: Set R_HOME for Julia
        shell: bash
        run: |
          R_HOME_PATH=$(Rscript -e 'cat(R.home())')
          echo "R_HOME=$R_HOME_PATH" >> $GITHUB_ENV
          export R_HOME=$R_HOME_PATH

      # 6. Set up Julia
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.11.5'
        env:
          JULIA_DEPOT_PATH: /home/runner/.julia

      # 7. Install Julia packages
      - name: Install Julia packages
        shell: julia {0}
        run: |
          ENV["R_HOME"] = get(ENV, "R_HOME", "")
          import Pkg
          Pkg.add("RCall")
          Pkg.add("Suppressor")
          Pkg.add("JuliaBUGS")

      # 8. Install R package dependencies
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::., any::devtools
          needs: website

      # 9. Build the package site
      - name: Build site
        run: Rscript -e 'pkgdown::build_site_github_pages(new_process = TRUE, install = TRUE)'

      # 10. Deploy site to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
