# macOS-exclusive pkgdown workflow with Julia and JAGS
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown-macos

permissions: write-all

jobs:
  pkgdown:
    runs-on: macos-latest
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      JULIA_DEPOT_PATH: /Users/runner/.julia
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      # Install JAGS for rjags
      - name: Install JAGS
        run: |
          brew update
          brew install jags
          brew link --force jags

      # Setup R
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: '4.4.1' # Ensure x86_64 binary (default runner arch)

      # Install rjags from source
      - name: Install rjags
        run: Rscript -e 'install.packages("rjags", type = "source")'

      # Determine and export R_HOME
      - name: Set R_HOME for Julia
        shell: bash
        run: |
          R_HOME_PATH=$(Rscript -e 'cat(R.home())')
          echo "R_HOME=$R_HOME_PATH" >> $GITHUB_ENV
          export R_HOME=$R_HOME_PATH
          echo "R_HOME set to $R_HOME"

      # Setup Julia
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.11.5'
        env:
          JULIA_DEPOT_PATH: /Users/runner/.julia

      # Install Julia packages including RCall
      - name: Install Julia RCall and JuliaBUGS
        shell: julia {0}
        run: |
          ENV["R_HOME"] = get(ENV, "R_HOME", "")
          import Pkg
          Pkg.add("RCall")
          Pkg.add("Suppressor")
          Pkg.add(url="https://github.com/TuringLang/JuliaBUGS.jl")
          using RCall
          my_range = 1:5
          @rput my_range
          println("RCall test successful")

      # Setup Pandoc
      - uses: r-lib/actions/setup-pandoc@v2

      # Install R dependencies for pkgdown
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::., any::devtools

      # Install package including vignettes
      - name: Install R package
        run: Rscript -e 'devtools::install(build = TRUE, build_vignettes = TRUE, upgrade = "never")'

      # Build site
      - name: Build pkgdown site
        shell: Rscript {0}
        run: pkgdown::build_site_github_pages(new_process = TRUE, install = TRUE)

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
