# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
on:
  push:
    branches:
      - main
      - mm/make_tests_ci_work_ubuntu
  pull_request:
    branches:
      - main
      - mm/make_tests_ci_work_ubuntu

name: R-CMD-check.yaml

permissions: read-all

jobs:
  R-CMD-check:
    # --- CHANGE 1: use Ubuntu 20.04 for Linux runners (stable for JuliaCall)
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-20.04,   r: 'devel', http-user-agent: 'release'}   # Ubuntu downgraded from latest
          - {os: ubuntu-20.04,   r: 'release'}                              # Ubuntu downgraded from latest
          - {os: ubuntu-20.04,   r: 'oldrel-1'}                             # Ubuntu downgraded from latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      CI: "true"
      JULIA_DEPOT_PATH: /tmp/julia-depot
      JULIA_NUM_THREADS: "1"

    steps:
      - uses: actions/checkout@v4

      - name: Prepare Julia depot
        run: mkdir -p /tmp/julia-depot

      # --- CHANGE 2: move setup-r BEFORE setup-pandoc & Julia to ensure R_HOME is set early
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.10.8'

      # --- CHANGE 3: explicitly export R_HOME for JuliaCall
      - name: Set R_HOME for Julia
        shell: bash
        run: |
          R_HOME_PATH=$(Rscript -e 'cat(R.home())')
          echo "R_HOME=$R_HOME_PATH" >> $GITHUB_ENV
          echo "R_HOME environment variable set to $R_HOME_PATH"

      # --- CHANGE 4: minimal safe Julia package setup for JuliaCall + rjuliabugs
      - name: Configure Julia packages
        shell: bash
        run: |
          echo "Using R_HOME for Julia: $R_HOME"
          # Install only necessary packages first to avoid precompilation conflicts
          julia -e 'import Pkg; Pkg.add(["RCall", "JuliaBUGS"])'
          julia -e 'ENV["R_HOME"] = ENV["R_HOME"]; import Pkg; Pkg.build("RCall")'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, any::devtools
          needs: check

      - name: Remove vignettes folder
        run: Rscript -e "if (dir.exists('vignettes')) unlink('vignettes', recursive=TRUE)"

      - name: Install package
        run: Rscript -e 'devtools::install(build_vignettes = FALSE, upgrade = "never")'

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--no-build-vignettes")'
